spring:
  application:
    name: aper_chat_back

  config:
    import:
      - classpath:/yml/application-local.yml
      - classpath:/yml/application-dev.yml
  profiles:
    active: local

logging:
  level:
    org:
      springframework:
        messaging:
          simp:
            stomp: DEBUG